theme_background:
  default: ""
  description:
    en: If you wish to change the default background add the url of the new background above.
theme_background_overlay:
  default: "theme automatic"
  type: enum
  choices:
    - theme automatic
    - dark overlay
    - nebula gradient
    - dragonfly gradient
  description:
    en: What colorway should the theme background overlay be?
rounded_interface_borders:
  default: false
  description:
    en: Enable rounded interface borders?
rounded_category_styles:
  default: false
  description:
    en: Enable rounded category styles?
avatar_shape:
  default: circle
  type: enum
  choices:
    - square
    - rounded
    - circle
  description:
    en: What shape should user avatars be in?
box_style_text-shadow:
  default: false
  description:
    en: Enable a text-shadow effect on category names, when using the box category style?
button_text_case:
  default: uppercase
  type: enum
  choices:
    - uppercase
    - capitalize
    - lowercase
  description:
    en: What text case should buttons have?
highlight_duration:
  default: 1.5
  min: 0.25
  max: 5
  description:
    en: How long – in seconds – should the highlight last?
